apiVersion: v1
kind: Secret
metadata:
  name: md-notifications-secret
stringData:
  mangadex_username: <mangadex_username>
  mangadex_password: <mangadex_password>
  discord_webhook_url: <discord_webhook_url>

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: md-notifications-config
data:
  style: compact
  sender_username: <sender_username>
  avatar_url: <avatar_url>

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: md-notifications-deployment
  labels:
    app: md-notifications
spec:
  replicas: 1
  selector:
    matchLabels:
      app: md-notifications
  template:
    metadata:
      labels:
        app: md-notifications
    spec:
      containers:
      - name: md-notifications
        image: docker.io/du0ng4/md-notifications:master
        imagePullPolicy: Always
        volumeMounts:
        - name: secret-volume
          mountPath: /etc/secret
        - name: config-volume
          mountPath: /etc/config
      volumes:
      - name: secret-volume
        secret:
          secretName: md-notifications-secret
      - name: config-volume
        configMap:
          name: md-notifications-config